### ISSUE TITLE
Realm error after updating to 2.1 

### ISSUE THREAD

**Issue by Bilonik** [realm/realm-dart#1643] opened 2024-04-18 22:31 UTC
### What happened?

First time to open, everything syncs.
Closing and opening the app and the Realm gives error:

     ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: Start read 57979: 38 ref 1946728)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query find all: '(state == 3 or state == 6)', limit = -1)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 491546152112: End transaction 60329)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query found: 1, Duration: 24 us)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query find all: 'state == 6', limit = -1)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query found: 0, Duration: 16 us)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: End transaction 57979)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 491546152112: Start read 58929: 38 ref 1946728)'
[ +198 ms] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: Start frozen 64129: 38 ref 1946728)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query find all: '(state == 3 or state == 6)', limit = -1)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query found: 1, Duration: 14 us)'
[   +3 ms] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: End transaction 64129)'
[   +3 ms] I/flutter (18286): Realm log message: '(category: Realm.SDK, level: LogLevel.error, message: Sync Error: error)'

### Repro steps

1.Open a sync realm
2.Close the app.
3. Open again
4. Gives error

### Version

2.1

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Android and iOS

### Relevant log output

```shell
] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: Start read 57979: 38 ref 1946728)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query find all: '(state == 3 or state == 6)', limit = -1)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 491546152112: End transaction 60329)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query found: 1, Duration: 24 us)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query find all: 'state == 6', limit = -1)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query found: 0, Duration: 16 us)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: End transaction 57979)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 491546152112: Start read 58929: 38 ref 1946728)'
[ +198 ms] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: Start frozen 64129: 38 ref 1946728)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query find all: '(state == 3 or state == 6)', limit = -1)'
[        ] I/flutter (18286): Realm log message: '(category: Realm.Storage.Query, level: LogLevel.debug, message: DB: 8565 Thread 490775493808: Query found: 1, Duration: 14 us)'
[   +3 ms] I/flutter (18286): Realm log message: '(category: Realm.Storage.Transaction, level: LogLevel.trace, message: DB: 8565 Thread 490775493808: End transaction 64129)'
[   +3 ms] I/flutter (18286): Realm log message: '(category: Realm.SDK, level: LogLevel.error, message: Sync Error: error)'
```

**Comment by tonisole** [comment] 2024-04-19 10:23
I have the same problem, when I open the app again the library Realm.SDK give me a Sync Error message "error" without a longer description.

**Comment by Bilonik** [comment] 2024-04-20 13:18
@tonisole , try this out: https://github.com/realm/realm-swift/issues/8531.

**Comment by tonisole** [comment] 2024-04-22 06:33
> @tonisole , try this out: [realm/realm-swift#8531](https://github.com/realm/realm-swift/issues/8531).

Hi @Bilonik, 

Thank you for your comment; it was instrumental in helping me resolve the issue.

When I download _"Pull front-end code"_ of my APP, I noticed that it was configured with "https://services.cloud.mongodb.com/" as the **baseUrl** and "https://eu-central-1.aws.services.cloud.mongodb.com/" as the **clientApiBaseUrl**. However, the demo code incorrectly used the baseUrl to synchronize with the server when it should have used the clientApiBaseUrl.

Replacing "https://services.cloud.mongodb.com/" with "https://eu-central-1.aws.services.cloud.mongodb.com/" in the configuration solved my problem.

I greatly appreciate your guidance in identifying the root cause of the issue.

**Comment by nielsenko** [comment] 2024-04-22 09:40
To elaborate. Your workaround works by supplying the location aware url directly as the `baseUrl`. You should not have to do that - we should figure it out for you.

**Comment by nielsenko** [comment] 2024-04-23 07:14
@tonisole and @Bilonik Can you share the appId of your apps? You can send them to me on kasper.nielsen@mongodb.com.

Also, if you can still reproduce, could I ask you to enable full tracing and upload the trace somewhere?

**Comment by nielsenko** [comment] 2024-05-03 07:33
@tonisole and @Bilonik A server-side fix for this was deployed April 24th.

Can you confirm that you no longer need the work-around? Then I will close this issue.

**Comment by tonisole** [comment] 2024-05-03 09:48
@nielsenko I can confirm that with the recent version of the library all work fine. Thank you!

**Closed** 2024-05-03 10:01 UTC
Labels: O-Community, Waiting-For-Reporter, T-Bug, SDK-Use:Sync
