### ISSUE TITLE
RealmException: Error getting property Userdata.isPro Error: RealmException: Error code: 7 . Message: Accessing object of type Userdata which has been invalidated or deleted

### ISSUE THREAD

**Issue by Navil** [realm/realm-dart#1198] opened 2023-03-06 11:02 UTC
### What happened?

After users install an app update or (sometimes) when reinstalling the app, I see the following error in Sentry:

> RealmException: Error getting property Userdata.isPro Error: RealmException: Error code: 7 . Message: Accessing object of type Userdata which has been invalidated or deleted

Apparently the userData object is synced, but it is not valid as the "current user"-print happens and afterwards I am getting errors all around the app, that that object is not valid.
Am I missing something here or is there a change that Realm is syncing an invalid object? The object is supposed to be valid at all times.

### Repro steps

I can't reproduce it on dev, but on prod it seems to happen after users install updates

### Version

Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.2604], locale de-AT)

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

1.0.2

### Code snippets

```
subscriptions.add(userdataQuery.changes.listen((changes) async {
      RealmResults<Userdata> realmResults = changes.results;
      if (!realmResults.isEmpty) {
        userdata = changes.results.first;
        if (userdata.role == "deleted") {
          return authService.accountDeleted();
        }
        userdataDone = true;
        notifyListeners();
        debugPrint("Current User: ${userdata.id}");
      }
}));
```

### Stacktrace of the exception/crash you're getting

```shell
RealmException: RealmException: Error getting property Userdata.isPro Error: RealmException: Error code: 7 . Message: Accessing object of type Userdata which has been invalidated or deleted
#0      RealmCoreAccessor.get (package:realm/src/realm_object.dart:213)
#1      RealmObjectBase.get (package:realm/src/realm_object.dart:316)
#2      Userdata.isPro (package:aupair/shared/model/realm.g.dart:1132)
#3      RealmService.isFreeUser (package:aupair/shared/services/realm_service.dart:252)
#4      _SharedSuggestionCarouselState.build (package:aupair/shared/widgets/carousel/suggestion_carousel.dart:53)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#14     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#18     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981)
#21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#31     StatelessElement.update (package:flutter/src/widgets/framework.dart:5044)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#35     StatelessElement.update (package:flutter/src/widgets/framework.dart:5044)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:5044)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#47     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#49     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981)
#50     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#54     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#59     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#64     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#79     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#95     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3660)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#99     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301)
```

### Relevant log output

![image](https://user-images.githubusercontent.com/3436399/223092967-f9c12d54-7114-4194-a43e-54bb76584deb.png)

**Comment by blagoev** [comment] 2023-03-06 11:16
This messages usually means that the code is accessing an invalidated/deleted object. You probably need a `userdata.isValid` check in the code. This might happen after an update if the sync subscriptions are recreated. This object that `is supposed to be valid at all times` might be invalidated. 
Without a reproduction it will be hard for us to investigate what might be the root cause of this.

**Comment by Navil** [comment] 2023-03-06 11:17
Thank you for the information. Will the subscription be re-triggered when the object is considered valid again ?

**Comment by blagoev** [comment] 2023-03-10 19:48
I suspect the object is invalidated cause after an update the subscriptions are recreated by the app. We will need some reproduction in order to be able to investigate this.

**Comment by Navil** [comment] 2023-03-10 20:17
I will try to add logging and reproduce it. Is is possible that subscriptions will be triggered with objects that are not valid?

**Comment by nielsenko** [comment] 2023-03-11 08:46
@Navil Do you by any chance add a new, but identical `UserProfile` with `realm.add(UserProfile(user.id, ...))` during startup, before ensuring you are sync'ed with `await realm.syncSession.waitForDownload()`?

**Comment by Navil** [comment] 2023-03-11 08:58
No, I am not. The userProfile is added on the server side after the user accepts the guidelines. On startup, I just create the queries.

**Comment by nielsenko** [comment] 2023-03-11 09:02
When you say server-side? How is that orchestrated? Do you use a realm sdk for it, or do you write straight to the MongoDB database? Do you check if a `UserProfile` already exists first?

**Comment by Navil** [comment] 2023-03-11 10:04
I just write to MongoDB directly from node and after that Realm will sync that object. Yes, I do that check on the backend. Even if not, the userId corresponds to the _id of that collection, so duplication would throw an error.  I am pretty sure that this is not what is happening, as restarting the client will not lead to calling that backend function. Somehow my sync is receiving an invalid object (see log and code snippet)

**Comment by nielsenko** [comment] 2023-03-11 10:32
The logs tell me your accessing an object that was deleted locally (despite it exists server-side), since it was first read. This can for example happen if the subscription/permission cover does not allow the object to exist at some point in time.

Could you show me where you setup your subscriptions, and also `RealmService.isFreeUser`?

**Comment by Navil** [comment] 2023-03-11 11:04
So, in my architecture I have 2 different types of users. Both call the common RealmService and then add their specific subscriptions/listeners on top. Userdata however is shared, so it is not touched by the specifc listeners anymore. I use the Provider package to create/dispose that RealmService on login/logout. So I also show the dispose method just in case as the problem happens more often after reinstalling/updating.

As this app is already production and more than just a small prototype, I tried to include everything thats important and I added comments for the lines that might not be obvious.

This is how my RealmService looks like:
```
RealmService(this.user, this.authService, this.isFamily) {
 setupSubscriptions();
}

@mustCallSuper
setupSubscriptions() async {
 ObjectId oid = ObjectId.fromHexString(user.id);

 RealmResults<Userdata> userdataQuery =
	realm.query<Userdata>('_id == "${user.id}"'); //I use strings for the id, as it is custom user data

 matchQuery = realm.query<Match>('userId == oid($oid)');

 chatRequestQuery =
	realm.query<ChatRequest>('userId == oid($oid));


 realm.subscriptions.update((MutableSubscriptionSet mutableSubscriptions) {
  mutableSubscriptions.add(userdataQuery);
  mutableSubscriptions.add(matchQuery);
  mutableSubscriptions.add(chatRequestQuery);
 });

 await realm.subscriptions.waitForSynchronization();

 // Listen for changes
 subscriptions.add(userdataQuery.changes.listen((changes) async {
  RealmResults<Userdata> realmResults = changes.results;
  if (!realmResults.isEmpty && changes.results.first.isValid) { // The isValid was added in my last version to test if it fixes the issue
	userdata = changes.results.first;
	userdataDone = true; //This tells the UI that it can stop showing the loading screen
	notifyListeners();
	debugPrint("Current User: ${userdata.id}");
  }
 }));

 subscriptions.add(chatRequestQuery.changes.listen((changes) {
  debugPrint("ChatRequests updated");
  notifyListeners();
 }));

 subscriptions.add(matchQuery.changes.listen((changes) async {
  realm.subscriptions.update((MutableSubscriptionSet mutableSubscriptions) {
	for (var match in changes.results) {
	  if (match.lastMessage != null) { //Load the lastMessage of a match to show it on the overview page
		RealmResults<Message> query =
			realm.query<Message>('_id == oid(${match.lastMessage})');
		if (realm.subscriptions.find<Message>(query) == null) {
		  mutableSubscriptions.add(query);
		}
	  }
	}
  });

  await realm.subscriptions.waitForSynchronization();
   notifyListeners();
  }));
 }

@override
void dispose() async {
 realm.subscriptions.update((MutableSubscriptionSet mutableSubscriptions) {
  mutableSubscriptions.clear();
 });
 for (StreamSubscription subscription in subscriptions) {
  subscription.cancel();
 }

 userdataDone = false;

 realm.close();
 super.dispose();
}
```

**Comment by nielsenko** [comment] 2023-03-11 12:27
It doesn't make me much wiser, sorry.. 

I'm not fan of you clearing the realm subscriptions in `dispose`.  The subscription cover is now empty, hence sync will start removing all objects. Depending on the timing (will sync finish before you exits) this will clear your database. This in turn will force you to fetch the data again, once the app restarts.

Is `RealmService.dispose` ever called in real-life? Or is `RealmService` a singleton that is never torn down?

As for ways forward..

The call to `Userdata.isPro` in the `RealmService.isFreeUser` (that is not included in the above code) could you try to guard it on the `UserData` object being valid, and if not try to read it by primary key from the database again and log what is happening to sentry?

Was the existing reference valid? If not, could another object be read from the realm with the same primary key, or not?

Maybe enable [breadcrumbs](https://docs.sentry.io/platforms/flutter/enriching-events/breadcrumbs/#customize-breadcrumbs) if you haven't already and sprinkle some strategic `Sentry.captureMessage` around.

I assume you cannot re-create in dev?

**Comment by Navil** [comment] 2023-03-11 12:47
`dispose` is called when the user is logging out (and I suppose when the app is closing - I dont get any logs of that function on the emulator when I close the application). Thus I dont want to have the subscriptions running anymore, do I?
It is a Singleton that will be disposed when it is removed from the widget tree. 

I tried guarding it, and then the next access to Userdata triggered the same issue. I could guard everything in my application but this sounds like the wrong approach.

Yes reading it manually via query (instead of managing the lifecycle by myself) was what I would have tried next.

I dont know if the reference was valid, sadly. According to the error, it was not. I will deploy again tomorrow, then I can add a few more logs.

I cannot recreate it on dev, correct.

**Comment by nielsenko** [comment] 2023-03-11 13:28
To be clear. I suggest you never clear the subscriptions, only update them. When you clear the subscriptions you are telling the sync engine to get rid of all objects in your realm, since they are all outside the subscription cover. The sync engine can do that really fast.

I don't suggest you guard everywhere, it was just to shed some light on when/why it happens.

**Comment by Navil** [comment] 2023-03-11 14:14
So I will no longer clear the subscriptions, instead I will update them like this now
`mutableSubscriptions.add(userdataQuery, name: "userdata", update: true);`

Is this what you would recommend? Any clever logs I could plant to improve the investigation?

**Comment by nielsenko** [comment] 2023-03-13 07:30
Yes, I recommend updating the subscriptions.

You can enable logging from the sync engine with:
```dart
  Realm.logger
    ..level = RealmLogLevel.detail
    ..onRecord.listen((event) {
      // send trace where you want
    });
```
Make sure to setup the log level before opening the realm

**Comment by nielsenko** [comment] 2023-03-16 09:13
@Navil Did you change the way subscriptions are handled? Ie. that they updated instead of deleted in dispose and recreated on startup? 

Regarding the non-breaking schema changes, and the potential impact on the validity of existing realm object references, I need to up-skill a bit. I will get back to you when I know more.

**Comment by Navil** [comment] 2023-03-16 09:21
@nielsenko Thank you for your efforts. Yes, I updated how subscriptions are handled. 

My dispose function looks like this now:
```
@override
  void dispose() async {
    for (StreamSubscription subscription in subscriptions) {
      subscription.cancel();
    }

    initializationDone = false;
    userdataDone = false;

    debugPrint("Dispose RealmService");

    realm.close();
    super.dispose();
  }
```

And I create subscriptions like this:
`mutableSubscriptions.add(userdataQuery, name: "userdata", update: true);`


I can provide any logs if you need. No idea how to export from Sentry tho.

**Comment by nielsenko** [comment] 2023-03-17 15:15
I ended up testing this, as the guy I want to talk to is on vacation. I will reach out to him later.

I tried making an additive schema change in developer mode on one device, and that did **not** trigger an invalidation of any realm objects on another device on the prior schema.

So wrt.
> Regarding the non-breaking schema changes, and the potential impact on the validity of existing realm object references in a live app...

It does not it seems (at least in in my test).

**Comment by Navil** [comment] 2023-03-17 19:04
Hmm thank you for the investigation. Any idea what this generic closing of the realm could mean?

**Comment by Navil** [comment] 2023-03-18 09:15
Also, I just have another theory. As it happens mostly on iOS (I just figured this out), is there maybe a difference how the realm behaves on iOS/Android when the app is updated? On both devices I stay logged in. According to the sentry events, after those updates the realm on iOS either throws a "permission changed" or "realm closed" error. I did not see those yet on Android.

**Comment by nielsenko** [comment] 2023-03-20 08:51
There are no differences at the dart level, except for the way the dynamic library is loaded. 

There are differences in realm-core, and probably in the flutter runtime between Android and iOS, but before fixating on this consider:

1.  App live-cycle is different between Android and iOS. 
2. There may be a demographic difference amongst your users. Perhaps hosts are more likely to own iPhones, and the codepath exercised is different between hosts and aupairs.

BTW, you also talk about "permission changed" and "realm closed" error, whereas we started by talking about "accessing .. invalidated or deleted" errors which is still what I'm focusing on.

**Comment by Navil** [comment] 2023-03-20 10:19
Hey, yes I am talking about those things because (according to the logs), something always happens that makes the Realm close/restart apparently. And this seems to happen on updating the application (on iOS?). I cannot reproduce it on an emulator at all, and timetraveling on TestFlight does also not reproduce it. 

In my history of over 100 devices, I actually only find iPhones and asian phones (Huawai, Xiaomi), but this could just be by chance. The logs show a disconnection from the realm and then a sync without any objects. After restarting, the issues are fixed.

Let me elaborate my understanding of the following sentry case (the original error often differs, sometimes it is a change in permission, sometimes jsut a close):
![image](https://user-images.githubusercontent.com/3436399/226310612-dfe8c054-5923-4716-ba44-079ef03b42c7.png)


1. Something happens on the update (iOS?) that triggers a reset or restart of the Realm
2. The currect User is loaded from the Realm
3. This print happens when my state thinks that everything is fine with login and populate the User to the logged in area, populating my Service that contains the Realm (so the user is now logged in and everything should be fine) 
4. Our listener for the values now gets empty lists of Userdata objects
5. Our UI breaks everywhere

So I have a new theory being, that - when updating on iOS, the old Realm does not close properly and then I create a second Realm and that one does not get any Objects as they are blocked by the old Realm. But this is just a theory. Not sure if this can depend on the vendor as Android seems to deal with that correct on some devices.

All my services get created when they are added to the Widget tree and removed when they are removed.

**Comment by nielsenko** [comment] 2023-03-20 10:33
How do you handle client resets?

**Comment by Navil** [comment] 2023-03-20 10:35
I am using the default handler. for both reset as well as syncErrors.

**Comment by nielsenko** [comment] 2023-03-20 11:12
Yes after a restart all you stale in-memory realm objects refs are removed and you start over, so it makes sense it works after a restart.

You are definitely holding on to some stale references, since:
```dart
  if (!realmResults.isEmpty && changes.results.first.isValid) { 
	userdata = changes.results.first;
```
won't update the `userdata` ref when changes are empty and I assume the existing ref is already invalid.

**Comment by Navil** [comment] 2023-03-20 11:25
Correct, but the sentry logs never show a sign of the "real data" arriving. The gray screen stays forever, meaning there never arrives an update with the objects.

**Comment by nielsenko** [comment] 2023-03-20 11:48
It is hard to speculate on without seeing the actual code.

BTW, What is causing the client resets? Did you change permissions(rules)?

**Comment by Navil** [comment] 2023-03-20 12:21
No I did not. In happens with every version and users updating (I guess). 

I could actually just narrow the issue down to a specific app version. It sadly startet after a major release of the app. I did however not change any dispose/create/... logic in that version. 

This is the only new code I added in my Service:
   ```
subscriptions.add(chatRequestQuery.changes.listen((changes) {
      notifyListeners();
    }));

    subscriptions.add(matchQuery.changes.listen((changes) async {
      realm.subscriptions.update((MutableSubscriptionSet mutableSubscriptions) {
        for (var match in changes.results) {
          RealmResults<Message> query =
              realm.query<Message>('_id == oid(${match.lastMessage})');
          if (realm.subscriptions.find<Message>(query) == null) {
            mutableSubscriptions.add(query);
          }
        }
      });

      await realm.subscriptions.waitForSynchronization();
      notifyListeners();
    }));
```

Also, I found that in that version we also upgraded the realm library:
![image](https://user-images.githubusercontent.com/3436399/226337526-6199fd50-8bf3-4d04-a51c-2ca4d3680732.png)

Not saying that the issue is on the end of realm, are you aware of any changes that happen in that regard with that version?

**Comment by dotjon0** [comment] 2023-03-20 13:21
Sorry not completely on topic - out of interest @nielsenko why:

`realm.query<Match>(r'userId == $0', [oid]);`
// over
`realm.query<Match>('userId == oid($oid)');`

Assume this is generally the best approach for any query in Realm?

**Comment by Navil** [comment] 2023-03-20 13:22
Thank you, for the input. 

This is how I am listening now. I did not use asyncMap before.
 ```
 subscriptions.add(matchQuery.changes.asyncMap((changes) async {
      realm.subscriptions.update((MutableSubscriptionSet mutableSubscriptions) {
        for (var match in changes.results) {
          if (match.lastMessage != null) {
            RealmResults<Message> query =
                realm.query<Message>('_id == oid(${match.lastMessage})');
            if (realm.subscriptions.find<Message>(query) == null) {
              mutableSubscriptions.add(query);
            }
          }
        }
      });

      await realm.subscriptions.waitForSynchronization();
      return true;
    }).listen((event) {
      notifyListeners();
    }));
```

What is the advantage of using a placeholder when syncing the objects?

I am not syncing every Message, i am just syncing the newest message of each match to show it on the "Matches" screen. Like "last message: 'Hello World'". I could connect them with 'or' if this makes any difference.

`userdataQuery.changes` gives me an empty list.

**Comment by nielsenko** [comment] 2023-03-20 13:30
@Navil You should also update the listener on `userdataQuery` to use `asyncMap` if you didn't already.

I think it would be an idea to trace the `changes` object in some details on that subscription:
```dart
subscriptions.add(userdataQuery.changes.asyncMap((changes) async {
  // trace the inserted, modified and deleted indexes
}).listen(...);
```

**Comment by Navil** [comment] 2023-03-20 13:31
Yes, I updated all of them, just wanted to make sure that I refactored it the correct way :)

I will deploy another version and check if I see any difference.

**Comment by Navil** [comment] 2023-03-20 13:41
The userdata listener usually runs no asynchronous code actually. Will the `async` flag alone have any impact on the issue you are suggesting?

Also this part has never changed in the past, but the `matchQuery` is async, was added in the version it broke and I refactored it now, just in case.

**Comment by nielsenko** [comment] 2023-03-20 17:38
No.

Dart futures start, even if no one awaits them, so if you have no await in your async function, it will run to completion immediately.

Still don't use listen with async functions, soon enough someone will add an await, and also exceptions are not propagated to `onError` etc. 
```dart
Future<void> myPrint(Object x) async {
  // await Future.value(0); // Uncomment to see the difference
  print(x);
}

Future<void> main(List<String> arguments) async {
  myPrint('Hello, ');
  print('World!');
}
```
outputs:
```
Hello, 
World!
```
unless you uncomment the marked line in which case it outputs:
```
World!
Hello, 
```

**Comment by nielsenko** [comment] 2023-03-24 10:30
I don't like those client resets. Can you provide the app_id and the sentry logs? Possibly out-of-bands

**Comment by nielsenko** [comment] 2023-03-24 10:41
A few .json files is fine for a start. I have seen people use the api (fx: https://gist.github.com/vladox/f401db999c5efdf2f25d38683fde2813) but I haven't tried it myself.

Google drive is convenient for me (kasper.nielsen@mongodb.com)

**Comment by nielsenko** [comment] 2023-03-24 11:14
Looking at the logs server-side I see:

> client file not found. The server has forgotten about the client-side file presented by the client. This is likely due to using a synchronized realm after terminating and re-enabling sync. Please wipe the file on the client to resume synchronization. { sessionIdent: 1, clientFileIdent: 840 } (ProtocolErrorCode=208)

Terminating and re-enabling sync will cause a client reset. The `Userdata` from before will no longer be valid, as bootstrap after reset progress, old refs will be invalid.

**Comment by nielsenko** [comment] 2023-03-24 11:26
BTW, I see some long `OR` expressions. Prefer to use `IN` instead. There is a very real limit to how deeply nested your `OR` expressions can be before exhausting the stack. 

Consider tagging objects with a _group id_ instead, and just have a query subscribing to that _group id_, if they are not "shared" among _groups_

**Comment by Navil** [comment] 2023-03-24 11:38
Thank you the insight. I fixed the OR expressions.

What are the reasons for a client reset to happen? And why breaks my app from it? Isnt there a way to "restart" the realm then?
My app does not recover when this error happens. Only restarting the app (sometimes even reinstalling) helps.

**Comment by nielsenko** [comment] 2023-03-24 11:52
Can you confirm you terminated sync in production at one time, and then later re-enabled it?

Clients that comes online after this will receive a client reset.

As this is handled existing refs risks becoming stale. Not only if the object is explicitly deleted, but also if it is recreated (what we sometimes refer to as erase/created). Full OT is not used during bootstrap.

Restarting will obviously refresh all refs (they are dart objects), hence why it helps.

Depending on how far along you are with the client-reset, once you restart, you may or may not see any more stale refs, after this.

It should never require a reinstall.

**Comment by Navil** [comment] 2023-03-24 11:53
Yes, in this concrete use-case I did. But I did not do it ever before yesterday. At that stage client resets happen for other reasons.

**Comment by nielsenko** [comment] 2023-03-24 13:16
It seems your current server side logs don't go that far back. The first error entry I see is from the 23rd.

But yes, it was still a client reset. You can read more about them, and why they happen [here](https://www.mongodb.com/docs/atlas/app-services/sync/error-handling/client-resets/#:~:text=A%20client%20reset%20error%20is,they%20perform%20a%20client%20reset.)

Currently you are using the default `RecoverOrDiscardUnsyncedChangesHandler`, but you can customize it, perhaps do some tracing with: `onBeforeReset`, `onAfterDiscard`, and `onAfterRecovery`.

The simplest approach is perhaps to wait for client resets to complete, and refetch all objects from the realm after that (refresh all your state).

It does get tricky fast, as the app version is not guaranteed to match your schema on the backend. You do not control when a user updates his app.

**Comment by Navil** [comment] 2023-03-24 13:18
I added a mechanism to force users to update (using this mainly for major updates).

Is there somewhere an example code to handle this scenario. How should it "normally" be handled? Client resets probably happen to everybody.

**Comment by nielsenko** [comment] 2023-03-24 13:37
Here is a place to [start](https://www.mongodb.com/docs/realm/sdk/flutter/sync/handle-sync-errors/#client-reset), but we don't have a sample for dart yet.

In general - not just for the sake of client resets - you need to listen for changes so you know when objects "dies". In the code above you assumed it couldn't happen and skipped changes with empty results. 

If you get a change notification with an empty results you know something must have died, otherwise it would not have been empty, or it wouldn't have been raised in the first place.

You can also look into using frozen objects those places where you don't benefit from the default liveness. Frozen object can never become stale. This can help you centralize where changes can occur and make it easier to reason about.

**Comment by Navil** [comment] 2023-03-28 06:26
Thank you for all your help.

Just to make sure, the website you linked says `The Realm SDK provides methods to automatically handle client resets in most scenarios.`

Does this stand true for the Flutter Realm SDK? The discussion here gives me the impression, that client resets are not really dealt with. 

Is it a smart idea to just close and open the realm again when I encounter my objects being removed from the realm?

Will they also be removed when the user logs out?

**Comment by nielsenko** [comment] 2023-06-13 12:02
@Navil I'm considering closing this. What is status on your end?

**Comment by Navil** [comment] 2023-06-13 14:25
Hey, I am still experiencing this issue. Everytime the realm has a client reset, this issue is happening.
Is the client reset handled by the realm SDK or do I need some form of recovering mechanism here?

**Comment by nielsenko** [comment] 2023-06-14 13:32
The client reset is handled automatically in that the db will in a consistently synced state after the default reset handling. However, the in-memory refs (RealmObject) your app holds **_may_** be invalidated in this process, if the underlying db object got deleted as part of the reset. You need to be prepared for that. The simplest approach is perhaps to refetch any realm object after a client reset to ensure your handles are valid.

**Closed** 2023-08-08 11:57 UTC
Labels: O-Community, Waiting-For-Reporter, T-Bug
