### ISSUE TITLE
toEjson() throws "Missing encoder for type RealmValue"

### ISSUE THREAD

**Issue by lhengl** [realm/realm-dart#1757] opened 2024-07-24 03:58 UTC
### What happened?

The toEjson() function throws when using RealmValue. The following error will be encountered:

`Missing encoder for type RealmValue`

### Repro steps

Define a Realm model with a RealmValue as a field.

Instantiate the model and then call the toEjson() function on the object.

### Version

Flutter 3.22.2

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Any

### Code snippets

class $MyClass {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  
  late RealmValue realmValue;
}

// instantiate and call toEjson()
final object = MyClass();

// this throws an error: "Missing encoder for type RealmValue"
object.toEjson();

**Comment by nielsenko** [comment] 2024-07-29 13:00
Thanks for reporting. This happen to be a duplicate of #1737 so I will close this one.

**Closed by nielsenko** 2024-07-29 13:00 UTC
Labels: O-Community, T-Bug, SDK-Use:Sync

**Comment by nielsenko** [comment] 2024-07-29 13:05
Duplicate of #1737
