### ISSUE TITLE
Don't include fields when value is NULL (unset when null?)

### ISSUE THREAD

**Issue by Rob-Biemans** [realm/realm-dart#1673] opened 2024-05-08 09:15 UTC
### Problem

Fields can be set "Optional", therefore the field with null as value will be saved in MongoDB. 

I prefer to not save the field at all and unset it instead.

### Solution

Add a 'unsetWhenNull' annotation/SchemaProperty for class level and class member level. This indicates to have the property/field not stored in database when value is null.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by nirinchev** [comment] 2024-05-08 09:26
This is not possible. The Realm database doesn't differentiate between null and unset.

**Comment by Rob-Biemans** [comment] 2024-05-08 09:40
> This is not possible. The Realm database doesn't differentiate between null and unset.

What if locally it is saved as null, but in just Atlas database not set?

**Comment by nirinchev** [comment] 2024-05-08 10:13
The problem is that MongoDB has support for both null and undefined/unset. Realm only has support for one of those, so we had to make a choice to consolidate around 1 thing - i.e. `null`. Is there a particular reason why you can't treat null on Atlas to be equivalent to unset?

**Comment by Rob-Biemans** [comment] 2024-05-08 10:21
@nirinchev Thank you for your time, we simply wish to reduce resources and therefore don't save fields that are not necessary when null in Atlas. It would not only save up resources, but also environmental benefits (i.e. less data/internet egress)

**Comment by nirinchev** [comment] 2024-05-08 10:30
I understand - have you measured the impact of this? In terms of Atlas Device Sync, there's no difference between null and undefined and we will not transfer information about fields that have their default values. I imagine if you have a rest API fetching the data directly from Atlas and serving it to consumers, that might generate larger payloads, but then it'd be up to you to setup your json serialization strategy to omit null values.

Finally, in terms of storage, yes, it'll have some impact, but in our experience, that is minimal as the data, rather than the field names uses up most storage.

**Comment by nirinchev** [comment] 2024-05-08 22:01
I'm going to close this as we have no immediate plans to support unsetting fields. We do have an upcoming project that would allow a more flexible schema design, similar to what we have in MongoDB, where we're discussing the option to remove fields. I've relayed this feedback to the team as a datapoint to consider during the design of the feature.

**Closed by nirinchev** 2024-05-08 22:01 UTC
Labels: O-Community, Importance:Major, SDK-Use:Sync
