### ISSUE TITLE
Question - Generating Realm models with named parameters for required and optional fields

### ISSUE THREAD

**Issue by n-doton** [realm/realm-dart#680] opened 2022-06-20 15:58 UTC
```
@RealmModel()
class _IceCream {
  late String flavour;
  late String cone;
  late int scoops;
}
```

When generating a Realm model from an _IceCream class as shown above, is there a way to force named fields for both required and optional parameters when creating or accessing an instance of IceCream? Currently, an instance is created like this:
```
IceCream iceCream = IceCream('vanilla', 'regular', 2)
```

However, we would prefer to name all parameters, as shown below:
```
IceCream iceCream = IceCream(flavour: 'vanilla', cone: 'regular', scoops: 2)
```

**Comment by lukaspili** [comment] 2022-06-21 23:53
Seems like a duplicate of #292

**Comment by desistefanova** [comment] 2022-06-23 13:18
Hi @n-doton,
You can find my answer and suggestion in [duplicated issue here](https://github.com/realm/realm-dart/issues/292#issuecomment-1164386306).

**Closed** 2022-06-28 12:57 UTC
Labels: O-Community, Waiting-For-Reporter
