### ISSUE TITLE
Run flutter web application, that uses realm for its mobile application.  

### ISSUE THREAD

**Issue by CodeHub95** [realm/realm-dart#1672] opened 2024-05-08 07:58 UTC
### What happened?

I have a flutter application that is using realm that supports only mobile and windows now the same code I want to run on web but for web we are not using realm. How can I handle imports and dependencies. 

### Repro steps

No link available.

Problem is like I have import on screens and dependencies in pubspec yaml file so it's giving error during web application development. 

### Version

3.16.9

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

15

**Comment by CodeHub95** [comment] 2024-05-08 07:58
Give me the solution as soon as possible

**Comment by nirinchev** [comment] 2024-05-08 09:28
This is a duplicate of https://github.com/realm/realm-dart/issues/1374

**Closed** 2024-05-08 09:29 UTC
Labels: O-Community, T-Bug, SDK-Use:Local
