### ISSUE TITLE
[Bug]: Disconnect because of session error

### ISSUE THREAD

**Issue by McSnowflake** [realm/realm-dart#913] opened 2022-09-19 07:49 UTC
### What happened?

I used a flexible sync to connect to mongo db app services, but the connection keeps on disconnecting with this error:

`I/flutter ( 7595): [INFO] Realm: Connection[1]: Session[1]: Received: ERROR "Other session level error: error while querying the state collection "state_Profile": (BadValue) cannot compare to undefined" (error_code=201, try_again=true, recovery_disabled=false)`
`I/flutter ( 7595): [INFO] Realm: Connection[1]: Disconnected`

### Repro steps

`Configuration config = Configuration.flexibleSync(currentUser, [Profile.schema], path: path);`
`_realm = Realm(config);`
 _realm.subscriptions.update((MutableSubscriptionSet subs) => subs.add(_realm.all<user.Profile>()));

... as per the [docs](https://www.mongodb.com/docs/realm/sdk/flutter/sync/open-synced-realm/)

`_realm.syncSession.connectionState` will report that it's connected, but afterwards it disconnects with mentioned error.

### Version

0.4.0+beta (also tried 0.3.2+beta -> same)

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

Android API 31

### Code snippets

`Configuration config = Configuration.flexibleSync(currentUser, [Profile.schema], path: path);`
`_realm = Realm(config);`
 _realm.subscriptions.update((MutableSubscriptionSet subs) => subs.add(_realm.all<user.Profile>()));

### Stacktrace of the exception/crash you're getting

```shell
I/flutter ( 7595): [INFO] Realm: Connected to endpoint '-.-.-.-:443' (from '-.-.-.-:43326')
D/EGL_emulation( 7595): app_time_stats: avg=268.90ms min=4.57ms max=1212.86ms count=8
I/flutter ( 7595): [INFO] Realm: Verifying server SSL certificate using 155 root certificates
I/flutter ( 7595): [INFO] Realm: Connection[1]: Session[1]: Received: ERROR "Other session level error: error while querying the state collection "state_Profile": (BadValue) cannot compare to undefined" (error_code=201, try_again=true, recovery_disabled=false)
I/flutter ( 7595): [INFO] Realm: Connection[1]: Disconnected
```

**Comment by desistefanova** [comment] 2022-09-19 08:00
Hi @McSnowflake,
Do you have some @Ignore annotations in your realm model?
Can you send your _Profile class?

**Comment by nirinchev** [comment] 2022-09-19 09:58
Can you set the client log level to `trace` and run your app again? While this does look like a server bug, having the client logs will help us confirm that.

**Comment by McSnowflake** [comment] 2022-09-20 18:01
> Hi @McSnowflake, Do you have some @ignore annotations in your realm model? Can you send your _Profile class?

Thanks for checking, here you go:

`@RealmModel()
class _Profile {
  @PrimaryKey()
  @MapTo('_id')
  late String id;
  late String type;
  late String lastname;
  late String firstname;
  late DateTime birthDate;
  late String sex;
  late String color;
  late String street;
  late int zipCode;
  late String city;
}`

**Comment by McSnowflake** [comment] 2022-09-20 18:34
> Can you set the client log level to `trace` and run your app again? While this does look like a server bug, having the client logs will help us confirm that.

Thanks for looking into it:
```
I/flutter (11629): [DETAIL] Realm: Connection[1]: Negotiated protocol version: 6
I/flutter (11629): [DEBUG] Realm: Connection[1]: Will emit a ping in 44675 milliseconds
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: IDENT(client_file_ident=28, client_file_ident_salt=..., scan_server_version=264, scan_client_version=5, latest_server_version=264, latest_server_version_salt=..., query_version: 0 query_size: 2, query: "{}")
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: QUERY(query_version=1, query_size=30, query="{"Profile":"(TRUEPREDICATE )"}"
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Limiting UPLOAD message up to version 13 to send QUERY version 2
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=13, progress_server_version=264, locked_server_version=264, num_changesets=1)
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Fetching changeset for upload (client_version=13, server_version=264, changeset_size=247, origin_timestamp=243502473632, origin_file_ident=0)
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Changeset: 3F 00 07 50 72 6F 66 69 6C 65 3F 01 1E 61 75 74 68 30 7C 36 33 32 32 30 62 64 66 62 36 30 63 31 63 66 30 39 62 30 32 37 61 31 32 02 00 03 01 3F 02 04 74 79 70 65 04 00 03 01 02 00 03 07 70 61 74 69 65 6E 74 00 3F 03 08 6C 61 73 74 6E 61 6D 65 04 00 03 01 03 00 03 03 42 61 6D 00 3F 04 09 66 69 72 73 74 6E 61 6D 65 04 00 03 01 04 00 03 03 4A 61 6D 00 3F 05 09 62 69 72 74 68 44 61 74 65 04 00 03 01 05 00 05 8F 94 D2 CB E7 41 00 00 3F 06 03 73 65 78 04 00 03 01 06 00 03 01 77 00 3F 07 05 63 6F 6C 6F 72 04 00 03 01 07 00 03 11 43 6F 6C 6F 72 28 30 78 66 66 32 39 36 37 61 33 29 00 3F 08 06 73 74 72 65 65 74 04 00 03 01 08 00 03 00 00 3F 09 07 7A 69 70 43 6F 64 65 04 00 03 01 09 00 01 00 00 3F 0A 04 63 69 74 79 04 00 03 01 0A 00 03 00 00
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: QUERY(query_version=2, query_size=30, query="{"Profile":"(TRUEPREDICATE )"}"
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Limiting UPLOAD message up to version 14 to send QUERY version 3
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=14, progress_server_version=264, locked_server_version=264, num_changesets=0)
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: QUERY(query_version=3, query_size=30, query="{"Profile":"(TRUEPREDICATE )"}"
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Limiting UPLOAD message up to version 15 to send QUERY version 4
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=15, progress_server_version=264, locked_server_version=264, num_changesets=0)
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: QUERY(query_version=4, query_size=30, query="{"Profile":"(TRUEPREDICATE )"}"
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Limiting UPLOAD message up to version 16 to send QUERY version 5
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=16, progress_server_version=264, locked_server_version=264, num_changesets=0)
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: QUERY(query_version=5, query_size=30, query="{"Profile":"(TRUEPREDICATE )"}"
I/flutter (11629): [TRACE] Realm: Connection[1]: Session[1]: Limiting UPLOAD message up to version 17 to send QUERY version 6
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=17, progress_server_version=264, locked_server_version=264, num_changesets=0)
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: QUERY(query_version=6, query_size=30, query="{"Profile":"(TRUEPREDICATE )"}"
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UPLOAD(progress_client_version=18, progress_server_version=264, locked_server_version=264, num_changesets=0)
I/flutter (11629): [TRACE] Realm: Connection[1]: Error message encoded as json: {"message":"Other session level error: error while querying the state collection \"state_Profile\": (BadValue) cannot compare to undefined","isRecoveryModeDisabled":false,"tryAgain":true,"logURL":"https://realm.mongodb.com/groups/.../apps/.../logs?co_id=...","shouldClientReset":false,"action":"Transient","backoffMaxDelaySec":300,"backoffIntervalSec":2,"backoffMultiplier":2}
I/flutter (11629): [INFO] Realm: Connection[1]: Session[1]: Received: ERROR "Other session level error: error while querying the state collection "state_Profile": (BadValue) cannot compare to undefined" (error_code=201, try_again=true, recovery_disabled=false)
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Suspended
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Will attempt to resume session after 8000 milliseconds
I/flutter (11629): [DEBUG] Realm: Connection[1]: Session[1]: Sending: UNBIND
I/flutter (11629): [DETAIL] Realm: Connection[1]: Allowing reconnection in 719 milliseconds
I/flutter (11629): [INFO] Realm: Connection[1]: Disconnected

**Comment by McSnowflake** [comment] 2022-09-20 18:36
Following the link provided in the logs it shows:
![grafik](https://user-images.githubusercontent.com/12428912/191337596-c3281aca-25c0-4d4f-ba28-61316dc2808e.png)

**Comment by McSnowflake** [comment] 2022-09-20 18:39
BTW: I may be just blind, but to get logs in a different level than info I had to edit the realm lib itself (i.e. there seems to be no way to pass the desired log level as param or config). Did I miss that?

```
  /// The logger to use for logging
  static Logger logger = Logger.detached('Realm')
    ..level = RealmLogLevel.trace
    ..onRecord.listen((event) => print(event));

in `.../realm-0.4.0+beta/lib/src/realm_class.dart`

**Comment by nirinchev** [comment] 2022-09-20 19:33
About the logger, you should be able to replace the built-in logger with one you provide like:

```dart
Realm.logger = Logger('my-logger')
  ..level = RealmLogLevel.trace
  ..onRecord.listen((event) => print(event));
```

Regarding the original issue - the server team mentioned this could be something to do with the read permissions you've defined for your data. Notably, if you're using an expansion on some custom user data field that doesn't exist. Can you share your permissions config as defined on the Device Sync section?

**Comment by McSnowflake** [comment] 2022-09-21 19:20
Thanks @nirinchev , that was it.
I changed the permissions to
```
{
  "rules": {},
  "defaultRoles": [
    {
      "name": "read-write",
      "applyWhen": {},
      "read": true,
      "write": true
    }
  ]
}

**Comment by McSnowflake** [comment] 2022-09-21 19:24
For completeness: before that I had the device sync permissions set to:
```
{
  "defaultRoles": [
    {
      "name": "owner-read-write", 
      "applyWhen": {},
      "read": {"_id": "%%user.id"},
      "write": {"_id": "%%user.id"}
    }
  ]  
}
```

But as I used JWT for authentication and had not yet set up the meta fields mapping, it couldn't find the `user.id` (at least that is what I asume)

**Comment by nirinchev** [comment] 2022-09-21 22:51
Yeah, that sounds exactly it. If the permission expansion ends up using a property that doesn't exist, you'll end up with that obscure error. We do have a task on the server to improve the error message to be more actionable, but that's not yet picked up.

**Comment by nirinchev** [comment] 2022-09-23 08:47
Closing this as the root cause was found. The server team already has a task to improve the messaging around the error, so nothing to do on the dart side.

**Closed by nirinchev** 2022-09-23 08:47 UTC
Labels: O-Community, Needs-Attention
