### ISSUE TITLE
How to handle these generator issues? Missing basic features of OOP

### ISSUE THREAD

**Issue by imSanjaySoni** [realm/realm-dart#1229] opened 2023-03-26 05:13 UTC
### Problem

I am facing these issues while migrating my flutter app from Hive to Realm DB, missing basic features of OOP.

**1. RealmModel should be a private class [ required prefix _ ]**
```
111 │ @RealmModel()
112 │ class TestRealm {}
    │       ^^^^^^^^^ missing prefix
    ╵
Align class name to match prefix [_$] (regular expression),
```

**2.  RealmModel can’t have a constructor**
```
111 │ @RealmModel()
112 │ class _TestRealm {
    │       ━━━━━━━━━━ in realm model for 'TestRealm'
113 │   const _TestRealm(this.name);
    │         ^^^^^^^^^^ has constructor
    ╵
Remove constructor
```

**3.  As RealmModel can’t have a constructor we have to make all variables as late**

**4.  RealmModel can’t extend any other class**
```
113 │ @RealmModel()
114 │ class _TestRealm extends Test {
    │       ^^^^^^^^^^ cannot extend Test
    ╵

```

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by nielsenko** [comment] 2023-03-26 12:25
Hi Sanjay

You are correct:

1.  Realm does not support polymorphism, 
2. all non-optional fields needs to be marked as `late`,
2. the constructor is generated for you, and
3. you need to prefix the model `_X` or `$X`, so that we can generate the `X` class.

The first restriction may be lifted, but not anytime soon.

The last three is by design. We did discuss using a [freezed](https://pub.dev/packages/freezed) like style for specifying models, avoiding the `late` keyword and allowing you to specify the constructor, but decided against it.

If you find these to be dealbreakers, then I'm afraid Realm is not for you.

**Closed** 2023-03-29 21:57 UTC
Labels: O-Community, Importance:Dealbraker
