### ISSUE TITLE
 The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.

### ISSUE THREAD

**Issue by vae260772** [realm/realm-dart#1756] opened 2024-07-22 03:49 UTC
### What happened?

Cache/hosted/pub.dev/realm_dart-2.3.0/lib/src/native/realm_core.dart:3602:59: Error: The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.
 - 'ByteBuffer' is from 'dart:typed_data'.
 - 'Uint8List' is from 'dart:typed_data'.
        return Uuid.fromBytes(Uint8List.fromList(listInt).buffer);

### Repro steps

Cache/hosted/pub.dev/realm_dart-2.3.0/lib/src/native/realm_core.dart:3602:59: Error: The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.
 - 'ByteBuffer' is from 'dart:typed_data'.
 - 'Uint8List' is from 'dart:typed_data'.
        return Uuid.fromBytes(Uint8List.fromList(listInt).buffer);

### Version

3.3.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

3.3.0

### Code snippets

 The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.

### Stacktrace of the exception/crash you're getting

```shell
The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.
```

### Relevant log output

```shell
The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.
```

**Comment by nirinchev** [comment] 2024-07-22 09:16
Duplicate of https://github.com/realm/realm-dart/issues/1729

**Closed by nirinchev** 2024-07-22 09:16 UTC
Labels: O-Community, T-Bug, SDK-Use:Local
