### ISSUE TITLE
Realm-flutter causes iPhone to crash and restart on iOS 17

### ISSUE THREAD

**Issue by pkumar8888** [realm/realm-dart#1411] opened 2023-10-03 13:57 UTC
### What happened?
I have been using Realm in my previous Flutter projects with no issue. But after upgrading to iOS 17 my iPhone keeps on crashing and restarting every time I start my previous apps with Realm. As soon as I remove Realm from the project, the crashes stop. Even the template sample app (flexi-sync flutter) crashes as soon as I create an account or login. I am on the Master channel (have tried 3.13 up until 3.16) of Flutter and am using iPhone 13 Pro Max running iOS 17.0.2

### Repro steps
1. Just install the template sample app (flexi-sync with atlas) and run the App.
1. As soon as you login or create an account and then login, the iOS device crashes and Restarts.

### Version
3.15 master

### What Atlas Services are you using?
Both Atlas Device Sync and Atlas App Services

### What type of application is this?
Flutter Application

### Client OS and version
iOS 17.0.2

**Comment by rogerkerse** [comment] 2023-10-03 17:48
We have same issue when building flutter app to real device with iOS 17. App crashes immediately and even device does some soft restart because of it.

We just have simple local realm.

**Comment by nielsenko** [comment] 2023-10-04 10:32
Same for me. Updated to the iOS 17.1 beta. Not only does the app never start, it soft restart the entire device.

Only happens on real devices, and when using realm. The default counter app does not cause any issues.
 
Here is a very minimal sample to provoke the issue:
```dart
import 'dart:isolate';

import 'package:flutter/material.dart';
import 'package:realm/realm.dart';

part 'main.g.dart';

@RealmModel()
class _Stuff {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
}

final realm = Realm(Configuration.local([Stuff.schema]));

void main() {
  Isolate.run(() {
    while (true) {
      realm.write(() => realm.add(Stuff(ObjectId())));
    }
  });
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: StreamBuilder(
        stream: realm.all<Stuff>().changes,
        builder: (context, snapshot) {
          final data = snapshot.data;
          return data == null
              ? const CircularProgressIndicator()
              : Material(
                  child: Center(child: Text('length: ${data.results.length}')),
                );
        },
      ),
    );
  }
}
```

**Comment by TimBudarick** [comment] 2023-10-08 16:12
I also have the same problem.

**Comment by kihong-hwang** [comment] 2023-10-14 14:57
Same here, crash with IOS 17 on my iPhone 15 pro with using realm.

**Comment by ymdkit** [comment] 2023-10-19 06:34
I also have same problem when schemaVersion is changed.

Device Info
iOS17
iPhone 15 Pro

**Comment by dotjon0** [comment] 2023-10-19 06:53
Any updates on this?

**Comment by pkumar8888** [comment] 2023-10-19 06:55
Unfortunately it seems that nobody from the flutter or the realm team really cares about realm on flutter..

**Comment by dotjon0** [comment] 2023-10-19 07:02
> Unfortunately it seems that nobody from the flutter or the realm team really cares about realm on flutter..

MongoDB have always been fast and fantastic in our experience, especially the Realm team. Must not be a simple fix.

**Comment by pkumar8888** [comment] 2023-10-19 07:07
> fix.

A simple note from the realm team that they are working on the issue or the fix will take time would have been really reassuring. But there has not been even a single official comment so far.

**Comment by nielsenko** [comment] 2023-10-22 14:35
> > Unfortunately it seems that nobody from the flutter or the realm team really cares about realm on flutter..
> 
> MongoDB have always been fast and fantastic in our experience, especially the Realm team. Must not be a simple fix.

As some of you may be aware I used to work for MongoDB on the Dart SDK for Realm (now called [_Atlas Device SDK_](https://www.mongodb.com/blog/post/realm-now-part-atlas-platform)). 

I feel obliged to inform you that I and the rest of the Dart team (among others) was laid off on September the 19th, so I'm afraid the prior level of support may falter, at least until the remaining people regroup. Still a lot of highly skilled engineers left at Realm - best I ever worked with.

But to be honest I'm not sure this github repo is actively monitored anymore, hence I recommend you reach out on the [forums](https://www.mongodb.com/community/forums/tag/flutter) instead. Even better to contact your account representative, if you have such one.

**Comment by dotjon0** [comment] 2023-10-22 14:42
> > > Unfortunately it seems that nobody from the flutter or the realm team really cares about realm on flutter..
> > 
> > MongoDB have always been fast and fantastic in our experience, especially the Realm team. Must not be a simple fix.
> 
> As some of you may be aware I used to work for MongoDB on the Dart SDK for Realm (now called [_Atlas Device SDK_](https://www.mongodb.com/blog/post/realm-now-part-atlas-platform)). 
> 
> I feel obliged to inform you that I and the rest of the Dart team (among others) was laid off on September the 19th, so I'm afraid the prior level of support may falter, at least until the remaining people regroup. Still a lot of highly skilled engineers left at Realm - best I ever worked with.
> 
> But to be honest I'm not sure this github repo is actively monitored anymore, hence I recommend you reach out on the [forums](https://www.mongodb.com/community/forums/tag/flutter) instead. Even better to contact your account representative, if you have such one.
> 
> 
> 
> 
> 
> 
> 
> 
> 

Really sorry to hear this and wish you all the best. Thank you for all your hard work and incredible support whilst at realm.

**Comment by liri2006** [comment] 2023-10-22 14:54
> > > Unfortunately it seems that nobody from the flutter or the realm team really cares about realm on flutter..
> > 
> > 
> > MongoDB have always been fast and fantastic in our experience, especially the Realm team. Must not be a simple fix.
> 
> As some of you may be aware I used to work for MongoDB on the Dart SDK for Realm (now called [_Atlas Device SDK_](https://www.mongodb.com/blog/post/realm-now-part-atlas-platform)).
> 
> I feel obliged to inform you that I and the rest of the Dart team (among others) was laid off on September the 19th, so I'm afraid the prior level of support may falter, at least until the remaining people regroup. Still a lot of highly skilled engineers left at Realm - best I ever worked with.
> 
> But to be honest I'm not sure this github repo is actively monitored anymore, hence I recommend you reach out on the [forums](https://www.mongodb.com/community/forums/tag/flutter) instead. Even better to contact your account representative, if you have such one.

OMG! This is a huge blow! Your dedication and care in Github issues were the main reason we decided to go with Realm.
Thank you for your work and good luck to you in your next endeavors!

If nothing changes in the matter of communication/support for Realm Dart in the next few days, we would be forced to look for alternatives.

**Comment by dotjon0** [comment] 2023-10-23 10:48
> forums

As @nielsenko mentioned, it sounds like the best approach for support/bug-reports are:

1. if you are a MongoDB enterprise customer -> then raise with your account executive / customer success manager
2. if you are not a MongoDB enterprise customer -> then raise via the [forums](https://www.mongodb.com/community/forums/tag/flutter)

Note: this is not official advice.

**Comment by liri2006** [comment] 2023-10-23 13:14
I've opened a topic regarding the future of Realm Dart on [MongoDb forum](https://www.mongodb.com/community/forums/t/realm-dart-future-plans/250348).

**Comment by nielsenko** [comment] 2023-10-24 12:21
There is a full reproduction project here: https://github.com/nielsenko/ios17_soft_reset.git

**Comment by nielsenko** [comment] 2023-10-24 14:13
Could you all try downgrading to Flutter 3.10.6, and report back?

**Comment by amondnet** [comment] 2023-10-26 05:44
https://github.com/dart-lang/sdk/issues/53859
https://github.com/dart-lang/sdk/commit/bd57548de127c0b7570f985d1969e54718474963

**Comment by nielsenko** [comment] 2023-11-01 10:38
@nirinchev I think it is safe to close this now. The fix is not released on flutter stable yet, but it is not related to Realm.

**Comment by nirinchev** [comment] 2023-11-01 11:21
Per @nielsenko's comment, this is being addressed by the flutter team in https://github.com/flutter/flutter/issues/136980 and https://github.com/dart-lang/sdk/issues/53859. We'll need to wait for them to release it, but the good news is that the crash appears to only affect debug builds, so applications distributed to end users should continue working.

**Closed by nirinchev** 2023-11-01 11:21 UTC
Labels: O-Community, T-Bug
