### ISSUE TITLE
Not fetching data while restart the application

### ISSUE THREAD

**Issue by Vimalananth** [realm/realm-dart#27] opened 2021-04-22 11:20 UTC
""Error: line 27 pos 3: native function 'Helpers_invokeStatic' (2 arguments) cannot be found""

**Comment by blagoev** [comment] 2021-05-14 10:05
Hi, thanks for reporting. This seems as a bug of our integration the flutter framework installed. The preview version has some known issues with hot reload and restart.  
As a workaround you can do `flutter run` from the command line.

**Comment by blagoev** [comment] 2021-05-14 10:06
closing this issue as no pending actions on it.

**Closed by blagoev** 2021-05-14 10:06 UTC
Labels: O-Community

**Comment by mariganesh555** [comment] 2021-07-13 18:59
still the issue is exist

"Exception has occurred.
_CompileTimeError ('package:realm/src/helpers.dart': error: line 27 pos 3: native function 'Helpers_invokeStatic' (2 arguments) cannot be found
  static dynamic invokeStatic(Type type, String name) native "Helpers_invokeStatic";
  ^
)"

<img width="1261" alt="Screenshot 2021-07-14 at 12 28 34 AM" src="https://user-images.githubusercontent.com/84121632/125509605-8249cc24-bb29-4483-a9d8-1926bb899274.png">
