### ISSUE TITLE
 Error: The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'

### ISSUE THREAD

**Issue by mbpatel6245** [realm/realm-dart#1731] opened 2024-06-25 09:44 UTC
### What happened?

During compile the Project we are getting below error

../../.pub-cache/hosted/pub.dev/ejson-0.3.0/lib/src/decoding.dart:246:92: Error: The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.
 - 'ByteBuffer' is from 'dart:typed_data'.
 - 'Uint8List' is from 'dart:typed_data'.
    {'\$binary': {'base64': String s, 'subType': '04'}} => Uuid.fromBytes(base64.decode(s).buffer),
                                                                                          ^
../../.pub-cache/hosted/pub.dev/ejson-0.3.0/lib/src/encoding.dart:120:63: Error: The method 'asUint8List' isn't defined for the class 'Uint8List'.
 - 'Uint8List' is from 'dart:typed_data'.
Try correcting the name to the name of an existing method, or defining a method named 'asUint8List'.
EJsonValue _encodeUuid(Uuid uuid) => _encodeBinary(uuid.bytes.asUint8List(), subtype: '04');
                                                              ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/realm_dart-3.0.0/lib/src/handles/native/to_native.dart:139:31: Error: The method 'asUint8List' isn't defined for the class 'Uint8List'.
 - 'Uint8List' is from 'dart:typed_data'.
Try correcting the name to the name of an existing method, or defining a method named 'asUint8List'.
    final bytes = value.bytes.asUint8List();
                              ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/realm_dart-3.0.0/lib/src/handles/native/from_native.dart:62:59: Error: The argument type 'ByteBuffer' can't be assigned to the parameter type 'Uint8List'.
 - 'ByteBuffer' is from 'dart:typed_data'.
 - 'Uint8List' is from 'dart:typed_data'.
        return Uuid.fromBytes(Uint8List.fromList(listInt).buffer);
                                                          ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

### Repro steps

During compile time when we run the project.

### Version

Flutter 3.22.2 • channel stable Framework • revision 761747bfc5 Engine • revision edd8546116 Tools • Dart 3.4.3 • DevTools 2.34.3 (3 weeks ago) • 2024-06-05 22:15:13 +0200 

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

macOS Sonoma version 14.5

**Comment by nielsenko** [comment] 2024-06-25 09:45
Duplicate of #1729

**Closed by nielsenko** 2024-06-25 09:45 UTC
Labels: O-Community, T-Bug, SDK-Use:Local
