### ISSUE TITLE
Realm (ejson) Type Conflict with Flutter Foundation Type

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1627] opened 2024-04-12 21:40 UTC
### What happened?

The name 'Key' is defined in the libraries 'package:ejson/src/types.dart' and 'package:flutter/src/foundation/key.dart'. (Documentation)

### Repro steps

Using Realm 2.0.0 with Flutter 3.19.0 has a type conflict between Flutter Foundation and the new ejson MongoDB (dependency of Flutter Realm).

Whilst there are workarounds for this, it would be very helpful if ejson did not cause such type conflicts with Flutter Foundation.

### Version

3.19.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

macOS

**Comment by nirinchev** [comment] 2024-04-12 21:42
This is a duplicate of https://github.com/realm/realm-dart/issues/1605 - we've changed the name and will release the fix in a future release (likely coming next week).

**Closed by nirinchev** 2024-04-12 21:41 UTC
Labels: O-Community, T-Bug, SDK-Use:Sync
